# NEVER EDIT THIS FILE MANUALLY
_commit: c113db2
_src_path: https://github.com/PaszaVonPomiot/copier-micropython-pico.git
project_description: Active buzzer examples in Micropython
project_name: micropython-active-buzzer
project_title: Active buzzer examples in Micropython
